version: '3.9'

services:

  postgres-usuarios:
    image: postgres:16-alpine
    container_name: notara-postgres-usuarios
    environment:
      POSTGRES_DB: notara-usuarios-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data
    networks:
      - notara-internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-notas-metas:
    image: postgres:16-alpine
    container_name: notara-postgres-notas-metas
    environment:
      POSTGRES_DB: notara-notas-metas-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_notas_metas_data:/var/lib/postgresql/data
    networks:
      - notara-internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    container_name: notara-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - notara-internal
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: notara-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - notara-internal
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_usuarios_data:
  postgres_notas_metas_data:
  mongo_data:
  redis_data:

networks:
  notara-internal:
    driver: bridge
